# Generated by Django 2.2 on 2020-01-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailIdfk', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'order_tbl',
            },
        ),
    ]
