# Generated by Django 2.2 on 2020-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='foodId',
            new_name='foodIdfk',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='emailIdfk',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart_tbl',
        ),
    ]
