# Generated by Django 2.2 on 2020-01-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20200118_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
