# Generated by Django 2.2 on 2019-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usermodel_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminEmail', models.CharField(max_length=20)),
                ('AdminPassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userType',
        ),
    ]
