# Generated by Django 2.2.3 on 2020-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20190904_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='AdminEmail',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
