# Generated by Django 2.2.3 on 2020-02-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200210_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='AdminEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='adminmodel',
            old_name='AdminPassword',
            new_name='Password',
        ),
    ]
